### ISSUE TITLE
Create Account for Expo and learn the basics

### ISSUE THREAD

**Issue by Fangedan** [CSAllenISD/2023-ISP-CafeProject#1]
Link: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwiH37b77rr8AhWSk2oFHRy8BxoQFnoECAkQAQ&url=https%3A%2F%2Fexpo.dev%2F&usg=AOvVaw1toPtYWURPMEWLLIhUw_Bt

**Comment by jakepodewils** [comment]
ok maybe later

**Comment by vvn1000** [comment]
im busy

**Comment by MustafaShihab1** [comment]
I will soon

**Comment by Fangedan** [comment]
Under the tab, Get Set Up & Create a build, press the Get Started button. Download the Expo Go app from apple store or google play store, then follow the directions to set up a mock expo app in your terminal (not codermerlin). Play around and discover new things about the app development process.

**Comment by Fangedan** [comment]
Guys we're scrapping Expo Go so disregard this entire issue. Also maybe find a way to label an issue as irrelevant in github :)
