### ISSUE TITLE
Set Up Visual Studios and Get Node.js **IMPORTANT**

### ISSUE THREAD

**Issue by vvn1000** [CSAllenISD/2023-ISP-CafeProject#12]
At school, install Visual Studio Code on Ubuntu. Once you are on Visual Studio Code, click on New File to create a new file and name it ____.js to make it a Javascript file. This is important because we are going to be coding on Javascript. Next, while still on Ubuntu, install Node.js through this link https://nodejs.org/en/ . Install the one that says recommended, not the one that says latest features. At home, do the same but for windows or macOS depending on what you have.

**Comment by Fangedan** [comment]
Done.

**Comment by saip9** [comment]
Everybody on Webex Teams has communicated to me that they were able to install the necessary tools for the project.

Marking the issue done on Friday February 17 2023 as task is finished.
