### ISSUE TITLE
Figure out whether we would like to publish an app or website

### ISSUE THREAD

**Issue by jakepodewils** [CSAllenISD/2023-ISP-CafeProject#16]

**Comment by jakepodewils** [comment]
Personally, I believe that creating an app would be the best idea, but we should start off with a website, so we can at least make a workable prototype.

**Comment by vvn1000** [comment]
I agree that we should do an app

**Comment by Fangedan** [comment]
One of our major discussion points was whether or not to implement the Cafe Project as a website or an app. We decided against the former as students would have to inconveniently find the link or search it up everytime they wanted to order, which would slightly defeat the purpose of convenience for our app. With an app, we deducted that student's could not only be able to access it with a tap on their phone but that they would also be able to reliably store sensitive data in the app itself, such as payment info, login username and passwords.
