### ISSUE TITLE
Create a rough draft of login/home screen of app, then collaborate with QA to make sure they understand your vision.

### ISSUE THREAD

**Issue by Fangedan** [CSAllenISD/2023-ISP-CafeProject#18]
This will primarily be technical elements of the design such as button placement, screens each button leads to, and accessibility and usability of the application.

**Comment by jakepodewils** [comment]
How are we going to be creating these rough drafs? Any specific applications that we are planning on using?

**Comment by Fangedan** [comment]
For now, since the MVP is due soon, I would recommend the easiest application to use for the rough draft, something like google slides to you can present the process of how it should work.

**Comment by MustafaShihab1** [comment]
I have a really good plane for the login page. I will go more in depth on it in person.

**Comment by saip9** [comment]
Moving to "Deleted" and marking as "duplicate" as this issue is addressed in other tasks and is redundant.
