### ISSUE TITLE
Find out how to label an issue as "resolved"

### ISSUE THREAD

**Issue by Fangedan** [CSAllenISD/2023-ISP-CafeProject#26]
The issue called: "Create repository 2023-ISP-CafeProject" seems to be completed, but I have no idea how to display it as resolved. Anyone know how to display an issue's completion?

Also find out how to label an issue as "irrelevant", we have decided to scrap the issue called: "Create Account for Expo and learn the basics" as we are not using Expo anymore, we are switching to Visual Studio.

**Comment by saip9** [comment]
Hi Andrew,
We are still planning to use Expo as we will be building an app. Please note that apps cannot be built on Microsoft Visual Studio Code. It is only used for writing code. To test our apps, Expo has to be used.
