### ISSUE TITLE
Add my github username to the README.md in my repository

### ISSUE THREAD

**Issue by saip9** [CSAllenISD/2023-ISP-CafeProject#28]
Adjacent to my username provide a list of role(s) for which I am responsible

Below my username (indented) add a link to my CoderMerlin Digital Portfolio

** Please comment below when this steps have been completed **

** When everyone has confirmed, we can move the issue to "Done" **

**Comment by Fangedan** [comment]
Thank you. If anyone still needs help editing the README.md file they can check the issue titled, "Edit README.md in Repository" for detailed step by step instructions.

**Comment by MustafaShihab1** [comment]
Thank you for the reminder. I have completed all the steps(DONE).

**Comment by vvn1000** [comment]
done

**Comment by jakepodewils** [comment]
I have officially completed this incredibly hard task. Thank you so much for the assignment, saip9!

**Comment by saip9** [comment]
Officially marked as done
