### ISSUE TITLE
Quality Check of Login Screen

### ISSUE THREAD

**Issue by MustafaShihab1** [CSAllenISD/2023-ISP-CafeProject#31]

**Comment by MustafaShihab1** [comment]
We are working on it right now and are almost done. It is going as planned.

**Comment by saip9** [comment]
Thank you @MustafaShihab1 for creating this issue. After the software engineers @vvn1000 and @jakepodewils have successfully created a login screen for the application, please check the following to ensure they followed good coding practices and designed a screen that clear of any distractions:

- Indented their lines of code
- Used functions whenever possible
- Placed comments through the file (have to meaningful and understandable) 
- Little to minimal redundancy 
- Overall output meets the MVP requirements 
- Clean UI (User Interface) design
- Follows through with the original expectations

Please let me know if they have followed the above rules diligently after the login screen is ready.

**Comment by saip9** [comment]
Altered the following to add more meaningfulness to the issue:

- Changed the tittle to "Quality Check of Login Screen"
- Added the label "Documentation"
- Added the priority as "MUST have"

**Comment by saip9** [comment]
@MustafaShihab1,

Please review the code and the design of the login screen carefully to ensure that industry guidelines have been met. Look at my previous comments to checklist of the things that have been done. Let me know here, through email, or Webex Teams your overall report of the login screen. I moving this issue to "Pending" as it is important that I get a quality report from you before proceeding to the next feature/enhancement.

**Comment by saip9** [comment]
@MustafaShihab1.

This is a reminder that this task is pending from you. It is essential that you have looked over the application which the software developers have created to ensure everything is followed properly. If you need to discuss further about this, you can message me on Webex Teams or email me.
