### ISSUE TITLE
Implementing Authentication and Database Functionalities

### ISSUE THREAD

**Issue by jakepodewils** [CSAllenISD/2023-ISP-CafeProject#35]
In order to create this project, we need a database side, and we need an actual application, so the website can save student's data, so they do not have to log in every single time. Let's start conducting some research on how we are going to do this, and develop a mock-up of our application.

**Comment by saip9** [comment]
First, I think we should code and design the basic outline of the app before going into complex functionalities. But, if I find any good resources about this, I will surely post them here.

**Comment by saip9** [comment]
@jakepodewils,
I think you should start working on the backend aspect of the app, as @vvn1000 has been primarily coding the frontend. Since we don't have a formal approval from the school administrative team for our project, we should try to create a sample database that we could test with our application. In the next few weeks, please research methods of creating and linking databases within our program. Please let me know if you have any questions.

**Comment by saip9** [comment]
@jakepodewils,

Here are some resources to help you to add database functionality to the login screen of our application. 

Official Expo Documentation
[Authentication with Google and AuthSession API](https://docs.expo.dev/guides/google-authentication/)
Youtube Video
[React Native Google Sign In with Expo](https://www.youtube.com/watch?v=FSMrzYpBeDM)

**Comment by saip9** [comment]
This issue is incorrectly categorized as "In Progress". No work has been started on this feature. So, moving this "Todo".

**Comment by saip9** [comment]
I have created the SQLite Database to use in the application. There many advantages to using this database such as: 

- Able to write commands using SQL
- ACID compliant (Atomicity, Consistency, Isolation and Durability)
- RDMS (Relational Database Mangement System)
- Open Source
- Free to use
- Large developer community support
- Lightweight and extremely fast

Resources:
[Official SQLite Website ](https://sqlite.org/index.html)
[Documentation](https://www.sqlite.org/docs.html)
[SQL Tutorial](https://www.youtube.com/watch?v=HXV3zeQKqGY)
[SQL Commands](https://www.w3schools.com/sql/)

Link to Commits:
Oldest to Newest
https://github.com/CSAllenISD/2023-ISP-CafeProject/commit/b37b2792f6763f0db247c16c969adf5cd17da0f1
https://github.com/CSAllenISD/2023-ISP-CafeProject/commit/ebcd248b1ea2ad3e0fc8615d8d6c6a058a9f180b
https://github.com/CSAllenISD/2023-ISP-CafeProject/commit/cbc259c30bd646ab43b4647a4105301782d19d1d
