### ISSUE TITLE
Get Webex Teams and Discord and Make a Groupchat

### ISSUE THREAD

**Issue by vvn1000** [CSAllenISD/2023-ISP-CafeProject#36]
Download these 2 apps if you don't already have them and join the groupchat. You will receive an invite in your emails for Webex Teams. Sai may leave further instructions.

**Comment by jakepodewils** [comment]
I firmly believe that Webex will be a great communication service for us. Thank you saip9 for discovering this wonderful application!

**Comment by mdraeed** [comment]
Added myself to the discord server.

**Comment by vvn1000** [comment]
Everyone has gotten Webex so I'm moving this to done.
