### ISSUE TITLE
Update GANTT chart

### ISSUE THREAD

**Issue by saip9** [CSAllenISD/2023-ISP-CafeProject#37]
Assigned to Project Manger and Product Manager
Update dates and project tasks

Link:
https://sharing.clickup.com/45028730/g/h/1ay5bu-1030/f761ef6bbcbf130

**Comment by Fangedan** [comment]
On it.

**Comment by saip9** [comment]
@Fangedan,

Please update dates and the project timeline. Also, make sure to add detailed tasks to the GANTT chart according to the advice given by Mr. Ben during the MVP presentation on Friday February 17 2023. I am requesting you to update the GANTT chart because it would be easier for the team to see what tasks have to be completed. So, there would be no communication gaps and enables you to manage the project more efficiently.

**Comment by saip9** [comment]
@Fangedan,

It has been two weeks since there was update about the progress of the GANTT chart. When I opened the chart, I saw no changes to the dates nor any modifications to the project tasks. I would request you to work on this as soon as possible incorporating the discussions we had from last few weeks and the feedback we received from the MVP presentation.

**Comment by saip9** [comment]
- Marking the issue as "Pending" 
@Fangedan 
Please let me know if you need any assistance while working on the GANNT chart. If needed, we can have a meeting on Webex Teams this week or next week to discuss further steps that are needed to be taken to ensure that project deliverables are being finished on time.

**Comment by Fangedan** [comment]
GANTT chart updated, complete with dates, and general summary of issues needed to be completed within specific time frames. Remember chart is subject to change, and the possibility is high as we encounter problems regarding development.
