### ISSUE TITLE
Watch this video on how to setup visual studio and expo together

### ISSUE THREAD

**Issue by vvn1000** [CSAllenISD/2023-ISP-CafeProject#40]
https://www.youtube.com/watch?v=1_WXNvK_tjs

Thats the link to the video. To be honest I watched it during class so I wasn't actually listening to what he was saying but it looks like he set it up properly. So hopefully its a helpful video.

**Comment by MustafaShihab1** [comment]
I have seen that video and it is helpful thank you for the link.

**Comment by saip9** [comment]
Information no longer needed as everybody has installed the necessary tools on the school computers and on their personal computers at home. Therefore, marking issue done on Friday February 17 2023.
