### ISSUE TITLE
Create MVP

### ISSUE THREAD

**Issue by Fangedan** [CSAllenISD/2023-ISP-CafeProject#41]
A minimum viable product (MVP) is a development technique in which a new product or website is developed with sufficient features to satisfy early adopters. The final, complete set of features is only designed and developed after considering feedback from the product's initial users. Please utilize an easy-access software to create the basic plan of how one is to interact with our app, starting from login following the process all the way until ordering/payment. Thank you.

**Comment by vvn1000** [comment]
When does this have to be done?

**Comment by Fangedan** [comment]
We are done.
