### ISSUE TITLE
Brainstorm ideas for advertisement poster

### ISSUE THREAD

**Issue by Fangedan** [CSAllenISD/2023-ISP-CafeProject#42]
https://d1csarkz8obe9u.cloudfront.net/posterpreviews/order-food-online-menu-design-template-0e977f5456dc33bd2274e7975e37aa68.jpg?ts=1637025395

I definitely feel like we should create a poster with similar elements to this one. This is because of it's feature of a phone, which directly implies to the audience that it is easily orderable online through a phone, except of course we would modify the names to match what is actually at Allen high school. However, this is indeed a online pizza ordering advertisement so this would be an almost perfect fit for the pizza hut at our school, also arguably the most popular.

**Comment by Fangedan** [comment]
If you two (the Product Manager and QA Engineer) can come to an agreement to create a poster similar to the one I included above, then you have permission to create a poster specified for The Cafe Project.

**Comment by saip9** [comment]
I have completed the Advertisement Poster using a tool called Canva. I have shared the poster through Webex Teams. Thus, marking the issue done on Friday February 17 2023 as task is finished.
