### ISSUE TITLE
Make a Logo

### ISSUE THREAD

**Issue by saip9** [CSAllenISD/2023-ISP-CafeProject#58]
Logos are found everywhere from coffee shops to mobile applications. Creating logos is not anything new, hundreds of centuries ago, Ancient Egyptians were among the first to start using symbols when they developed hieroglyphics. Later in 1870s, the first official logos for businesses appeared. Logos are often used to attract consumer attraction and to make a first good impression, which would lead to more interest in the company.   @saip9 will create a logo to be utilized in the app and in marketing material.

**Comment by saip9** [comment]
I have used Adobe Express to a create logo for this project. Furthermore, I have found the website to be easy and nice to use as it asks you simple questions at the beginning and generates a couple of designs based on the previous answers. You can then also choose to modify the design to your own liking. It has a wealth of tools to make enhancements to the logo. In addition, I have replaced the temporary logo with the new logo and pushed the code to GitHub repository. 

Here are the screenshoots of logo:


![Image](https://user-images.githubusercontent.com/89651922/226075139-cd87ec82-9e61-4316-8a99-72db3b0f20dd.png)


![Image](https://user-images.githubusercontent.com/89651922/226075167-94ba3fd0-52e6-40b8-b9b4-53c5e21a3f3d.png)

- Therefore, closing the issue on Friday March 17 2023 as initial conditions have been met.

**Comment by MustafaShihab1** [comment]
Love it. Its how we wanted it.
