### ISSUE TITLE
Scroll View (Menu Screen)

### ISSUE THREAD

**Issue by saip9** [CSAllenISD/2023-ISP-CafeProject#64]
If I am trying to add more menu items on screen, I am not able to view it because the screen is set to static view. The issue has to be resolved quickly because we have only menu item in the app. Initially, I tried to implement this feature but I was facing many issues such as the screen becoming unresponsive, and the layout of the app getting disarranged. So, it would be great if somebody could help me with this aspect of the application. 

Here are some resources that could help in implementing this enhancement:
- [React Native Documentation](https://reactnative.dev/docs/scrollview)
- [TutorialsPoint Code Sample](https://www.tutorialspoint.com/react_native/react_native_scrollview.htm)
- [React Native School YouTube Tutorial](https://www.youtube.com/watch?v=riWf6CtFkUA)

**Comment by MustafaShihab1** [comment]
I have checked the code in  MenuScreen.js and the Scroll Bar works.
