### ISSUE TITLE
Scroll Bar issue

### ISSUE THREAD

**Issue by MustafaShihab1** [CSAllenISD/2023-ISP-CafeProject#65]
As we tested the Scroll Bar on our project we found out the there was an issue with it. The one issue is it cut the screen in half. You can see the top of the screen but the rest is cut out and its just a white page. We found a way to make it better where you can see more of the page, By adding more Stuff of the page you can see about 2/3 of the screen.

**Comment by saip9** [comment]
Hi @MustafaShihab1 ,

An issue has already created before regarding the inability to scroll down the MenuScreen which is inhibiting the adding of other items below the original one, I would request to the close this issue. 

Please use this for further discussion:
https://github.com/CSAllenISD/2023-ISP-CafeProject/issues/64
