### ISSUE TITLE
Name Input and Item Display (Checkout Screen)

### ISSUE THREAD

**Issue by Fangedan** [CSAllenISD/2023-ISP-CafeProject#67]
On 4/24/2023, the team agreed on issues assigned for the week. This week, our goal is to complete the minimum viable product for the checkout screen. After discussion with @saip9 , I have discovered our current working transferrable variables, which are menu item names and their respective prices. We have decided that the checkout screen will (once finished) allow users to input items based on their "codes" (ex. burger is the result of a user inputting the number 100) and also input names for verification into a sql database that we will use later on the administrator side of the app. Our goal will be figuring out how to implement these into a working Android and iOS application, as so far the iOS is incomplete and the Android simply crashes.

Best of luck to us all.

**Comment by saip9** [comment]
@Fangedan 
Please note that the above description is not sufficient for the project team to resolve and request you to delete this as soon as possible. For further discussion about the topics mentioned in your message, please refer to the following issues I created:

[https://github.com/CSAllenISD/2023-ISP-CafeProject/issues/68](https://github.com/CSAllenISD/2023-ISP-CafeProject/issues/68)
[https://github.com/CSAllenISD/2023-ISP-CafeProject/issues/69](https://github.com/CSAllenISD/2023-ISP-CafeProject/issues/69)

**Comment by saip9** [comment]
@Fangedan, 
The GANTT chart link that you @Fangedan have sent in Webex Teams is not working as it is saying I don't have permission to view the document. I have messaged and called you several times but you have not responded.
